### PR TITLE
SVCPLAN-5555: Add support for SUSE

### PR DESCRIPTION
**Pull request by billglick**
This is being tested on `control-test-opensuse155a`.

### CODE REVIEW

**Review by jakerundall — COMMENTED** [review]
Something's not working with the ldap_tls_cacert override — it's not being applied on the machine even though it makes it into the environment on control-pup01.

Oh...I guess it's being overridden by environment hiera as set in common.yaml. I guess we'll have to further override it the control repo? Can we it by OS there? (We'd have to add another Hiera layer I suppose.)

**Comment by billglick** [comment]
> Something's not working with the ldap_tls_cacert override ...

My current fix... 

1. Set a new `sssd::default_tls_cacert` for each supported OS family in this `sssd` module.
2. Then reference that in the `sssd::domains` data in the control repo's `data/common.yaml` via: `ldap_tls_cacert: "%{lookup('sssd::default_tls_cacert')}"`

This seems to work, but is a bit of an odd approach. The concern I have is that the `sssd` module doesn't really make use of this parameter so it ends up being undocumented in the REFERENCE.md, etc files in the `sssd` module. 

Any thoughts on how this could be improved to not feel like a hack?

**Comment by jakerundall** [comment]
Could we define `default_tls_cacert` as a param for the `sssd::domain` defined resource type and adjust the data-in-module so that `sssd::domain::default_tls_cacert` is the key instead, which would pull that per-OS data in automatically? (I imagine we can do that with a defined resource type, not just classes?)

And then in `domain.pp` have a conditional that sets `ldap_tls_cacert` equal to any user specified value, if present, otherwise it falls back on the `default_tls_cacert` value?

And then pull the `ldap_tls_cacert` value out altogether from `common.yaml` in `control-repo` and `delta-control` (and anywhere else we might like to do that)?

**Comment by billglick** [comment]
I think we would want to replace https://github.com/ncsa/puppet-sssd/blob/a96f2bc94e33531ef6e7f4521380c12e3f628198/manifests/config.pp#L88-L92 with something like:

```
  $::sssd::domains.each |$resource, $attributes| {
    # IF $attributes DOES NOT CONTAIN tls_cacert AND ! empty( $::sssd::default_tls_cacert )
    #   $updated_attributes = $attributes + { 'tls_cacert' => $::sssd::default_tls_cacert }
    # ELSE
    #   $updated_attributes = $attributes 
    ::sssd::domain { $resource:
      * => $attributes,
      #* => $updated_attributes,
    }
  }
```

**Review by jakerundall — APPROVED** [review]
This approach looks good. I assume you tested the various scenarios, in which case merge away.

**Comment by billglick** [comment]
I've made a couple more changes since this was originally approved:
- Added additional packages to `sssd::package_name` for Suse

**Pull request merged**
